/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BUSDMock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BUSDMock__factory>
getContractFactory(name: 'CampaignProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CampaignProxy__factory>
getContractFactory(name: 'CampaignFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CampaignFactory__factory>
getContractFactory(name: 'CampaignFactoryProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CampaignFactoryProxy__factory>
getContractFactory(name: 'CampaignVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CampaignVault__factory>

  getContractAt(name: 'BUSDMock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BUSDMock>
getContractAt(name: 'CampaignProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CampaignProxy>
getContractAt(name: 'CampaignFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CampaignFactory>
getContractAt(name: 'CampaignFactoryProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CampaignFactoryProxy>
getContractAt(name: 'CampaignVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CampaignVault>

  deployContract(name: 'BUSDMock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BUSDMock>
deployContract(name: 'CampaignProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignProxy>
deployContract(name: 'CampaignFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignFactory>
deployContract(name: 'CampaignFactoryProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignFactoryProxy>
deployContract(name: 'CampaignVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignVault>

  deployContract(name: 'BUSDMock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BUSDMock>
deployContract(name: 'CampaignProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignProxy>
deployContract(name: 'CampaignFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignFactory>
deployContract(name: 'CampaignFactoryProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignFactoryProxy>
deployContract(name: 'CampaignVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CampaignVault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  