/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aumFinTokenSol from './AumFinToken.sol/index.js';
export type { aumFinTokenSol };
import type * as campaignSol from './campaign.sol/index.js';
export type { campaignSol };
import type * as campaignfactorySol from './campaignfactory.sol/index.js';
export type { campaignfactorySol };
export * as factories from './factories/index.js';
export type { AumFinBEPToken } from './AumFinToken.sol/AumFinBEPToken.js';
export { AumFinBEPToken__factory } from './factories/AumFinToken.sol/AumFinBEPToken__factory.js';
export type { CampaignVault } from './campaign.sol/CampaignVault.js';
export { CampaignVault__factory } from './factories/campaign.sol/CampaignVault__factory.js';
export type { CampaignFactory } from './campaignfactory.sol/CampaignFactory.js';
export { CampaignFactory__factory } from './factories/campaignfactory.sol/CampaignFactory__factory.js';