/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Structs {
      
    export type DeployParamsStruct = {admin: AddressLike, signer: AddressLike, _name: string, _symbol: string, asset: AddressLike, goal: BigNumberish, _minInvestment: BigNumberish, _maxInvestment: BigNumberish, _startTime: BigNumberish, _endTime: BigNumberish, _tokenPrice: BigNumberish, _payoutType: BigNumberish, maturityTime: BigNumberish, interestPermile: BigNumberish}

    export type DeployParamsStructOutput = [admin: string, signer: string, _name: string, _symbol: string, asset: string, goal: bigint, _minInvestment: bigint, _maxInvestment: bigint, _startTime: bigint, _endTime: bigint, _tokenPrice: bigint, _payoutType: bigint, maturityTime: bigint, interestPermile: bigint] & {admin: string, signer: string, _name: string, _symbol: string, asset: string, goal: bigint, _minInvestment: bigint, _maxInvestment: bigint, _startTime: bigint, _endTime: bigint, _tokenPrice: bigint, _payoutType: bigint, maturityTime: bigint, interestPermile: bigint }
  
    }

export declare namespace CampaignVault {
      
    export type SignStruct = {v: BigNumberish, r: BytesLike, s: BytesLike, nonce: BigNumberish, deadline: BigNumberish}

    export type SignStructOutput = [v: bigint, r: string, s: string, nonce: bigint, deadline: bigint] & {v: bigint, r: string, s: string, nonce: bigint, deadline: bigint }
  

    export type InvestmentDetailStruct = {amount: BigNumberish, allocatedShares: BigNumberish, timeStamp: BigNumberish}

    export type InvestmentDetailStructOutput = [amount: bigint, allocatedShares: bigint, timeStamp: bigint] & {amount: bigint, allocatedShares: bigint, timeStamp: bigint }
  

    export type UserDetailStruct = {investments: CampaignVault.InvestmentDetailStruct[], totalAllocatedShares: BigNumberish, lastclaimedIndex: BigNumberish, lastclaimTimestamp: BigNumberish}

    export type UserDetailStructOutput = [investments: CampaignVault.InvestmentDetailStructOutput[], totalAllocatedShares: bigint, lastclaimedIndex: bigint, lastclaimTimestamp: bigint] & {investments: CampaignVault.InvestmentDetailStructOutput[], totalAllocatedShares: bigint, lastclaimedIndex: bigint, lastclaimTimestamp: bigint }
  
    }

  export interface CampaignVaultInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "DEPOSIT_FEE_PERMILE" | "ENDTIME" | "FUNDING_CAP" | "MATURITY_INTEREST_PERMILE" | "MATURITY_TIME" | "MAX_DEPOSIT" | "MIN_DEPOSIT" | "PAYOUT_TYPE" | "STARTTIME" | "TOKEN_PRICE" | "TOTAL_INVESTMENTS" | "WITHDRAW_FEE_PERMILE" | "admin" | "allowance" | "approve" | "asset" | "balanceOf" | "claim" | "convertToAssets" | "convertToShares" | "decimals" | "deposit" | "depositWithSign" | "feedFunds" | "getROI" | "getRoleAdmin" | "getUserDetails" | "getmaturityROI" | "grantRole" | "hasRole" | "maxDeposit" | "maxMint" | "maxRedeem" | "maxWithdraw" | "mint" | "name" | "pause" | "paused" | "previewDeposit" | "previewMint" | "previewRedeem" | "previewWithdraw" | "redeem" | "renounceRole" | "rescueTokens" | "revokeRole" | "signAuthority" | "supportsInterface" | "symbol" | "totalAssets" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "unpause" | "withdraw" | "withdrawFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "Deposit" | "FUNDSAdded" | "OwnerChanged" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Transfer" | "Unpaused" | "Withdraw" | "withdrawnFunds"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEPOSIT_FEE_PERMILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ENDTIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'FUNDING_CAP', values?: undefined): string;
encodeFunctionData(functionFragment: 'MATURITY_INTEREST_PERMILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MATURITY_TIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_DEPOSIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DEPOSIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAYOUT_TYPE', values?: undefined): string;
encodeFunctionData(functionFragment: 'STARTTIME', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOKEN_PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOTAL_INVESTMENTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WITHDRAW_FEE_PERMILE', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'convertToAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'convertToShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'depositWithSign', values: [BigNumberish, CampaignVault.SignStruct]): string;
encodeFunctionData(functionFragment: 'feedFunds', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getROI', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getUserDetails', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getmaturityROI', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'maxDeposit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxMint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxRedeem', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewMint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewRedeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'rescueTokens', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'signAuthority', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFunds', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEPOSIT_FEE_PERMILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ENDTIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FUNDING_CAP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MATURITY_INTEREST_PERMILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MATURITY_TIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_DEPOSIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DEPOSIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAYOUT_TYPE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STARTTIME', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOKEN_PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOTAL_INVESTMENTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WITHDRAW_FEE_PERMILE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositWithSign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feedFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getROI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getmaturityROI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rescueTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFunds', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [sender: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FUNDSAddedEvent {
      export type InputTuple = [amount: BigNumberish, index: BigNumberish, time: BigNumberish];
      export type OutputTuple = [amount: bigint, index: bigint, time: bigint];
      export interface OutputObject {amount: bigint, index: bigint, time: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerChangedEvent {
      export type InputTuple = [prevAdmin: AddressLike, newUser: AddressLike];
      export type OutputTuple = [prevAdmin: string, newUser: string];
      export interface OutputObject {prevAdmin: string, newUser: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, receiver: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace withdrawnFundsEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CampaignVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): CampaignVault;
    waitForDeployment(): Promise<this>;

    interface: CampaignVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEPOSIT_FEE_PERMILE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ENDTIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FUNDING_CAP: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MATURITY_INTEREST_PERMILE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MATURITY_TIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_DEPOSIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DEPOSIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAYOUT_TYPE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STARTTIME: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOKEN_PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOTAL_INVESTMENTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WITHDRAW_FEE_PERMILE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    convertToAssets: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    convertToShares: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    depositWithSign: TypedContractMethod<
      [assets: BigNumberish, sign: CampaignVault.SignStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    feedFunds: TypedContractMethod<
      [_amount: BigNumberish, _from: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    getROI: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getUserDetails: TypedContractMethod<
      [user: AddressLike, ],
      [CampaignVault.UserDetailStructOutput],
      'view'
    >
    

    
    getmaturityROI: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxDeposit: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxMint: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxRedeem: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxWithdraw: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    previewDeposit: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewMint: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewRedeem: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewWithdraw: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rescueTokens: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    signAuthority: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newUser: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    withdrawFunds: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEPOSIT_FEE_PERMILE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ENDTIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FUNDING_CAP'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MATURITY_INTEREST_PERMILE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MATURITY_TIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_DEPOSIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DEPOSIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAYOUT_TYPE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STARTTIME'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOKEN_PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOTAL_INVESTMENTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WITHDRAW_FEE_PERMILE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'convertToAssets'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'convertToShares'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositWithSign'): TypedContractMethod<
      [assets: BigNumberish, sign: CampaignVault.SignStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feedFunds'): TypedContractMethod<
      [_amount: BigNumberish, _from: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getROI'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserDetails'): TypedContractMethod<
      [user: AddressLike, ],
      [CampaignVault.UserDetailStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getmaturityROI'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxDeposit'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxMint'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxRedeem'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxWithdraw'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'previewDeposit'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewMint'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewRedeem'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewWithdraw'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rescueTokens'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signAuthority'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newUser: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFunds'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'FUNDSAdded'): TypedContractEvent<FUNDSAddedEvent.InputTuple, FUNDSAddedEvent.OutputTuple, FUNDSAddedEvent.OutputObject>;
getEvent(key: 'OwnerChanged'): TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
getEvent(key: 'withdrawnFunds'): TypedContractEvent<withdrawnFundsEvent.InputTuple, withdrawnFundsEvent.OutputTuple, withdrawnFundsEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Deposit(address,address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'FUNDSAdded(uint256,uint256,uint256)': TypedContractEvent<FUNDSAddedEvent.InputTuple, FUNDSAddedEvent.OutputTuple, FUNDSAddedEvent.OutputObject>;
      FUNDSAdded: TypedContractEvent<FUNDSAddedEvent.InputTuple, FUNDSAddedEvent.OutputTuple, FUNDSAddedEvent.OutputObject>;
    

      'OwnerChanged(address,address)': TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
      OwnerChanged: TypedContractEvent<OwnerChangedEvent.InputTuple, OwnerChangedEvent.OutputTuple, OwnerChangedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdraw(address,address,address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    

      'withdrawnFunds(uint256)': TypedContractEvent<withdrawnFundsEvent.InputTuple, withdrawnFundsEvent.OutputTuple, withdrawnFundsEvent.OutputObject>;
      withdrawnFunds: TypedContractEvent<withdrawnFundsEvent.InputTuple, withdrawnFundsEvent.OutputTuple, withdrawnFundsEvent.OutputObject>;
    
    };
  }