/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as aumFinTokenSol from './AumFinToken.sol/index.js';
export * as campaignSol from './campaign.sol/index.js';
export * as campaignfactorySol from './campaignfactory.sol/index.js';