// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Structs$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Structs";
  readonly sourceName: "contracts/utils/struct.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220679c033ba0aa9984881c1873abaf5180663a50b3fbf686f6faa48a315e40d85e64736f6c634300081e0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220679c033ba0aa9984881c1873abaf5180663a50b3fbf686f6faa48a315e40d85e64736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/struct.sol";
  readonly buildInfoId: "solc-0_8_30-2d0e136125f185bdfdaa8c35d2132da9c6a53159";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Structs"]: Structs$Type;
    ["contracts/utils/struct.sol:Structs"]: Structs$Type;
  }
}