/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as campaignBeaconSol from './CampaignBeacon.sol/index.js';
export type { campaignBeaconSol };
import type * as campaignFactoryImpSol from './campaignFactoryImp.sol/index.js';
export type { campaignFactoryImpSol };
import type * as campaignVaultImpSol from './campaignVaultImp.sol/index.js';
export type { campaignVaultImpSol };
export type { CampaignFactoryProxy } from './CampaignFactoryProxy.js';